# Generated by Terraform (modules/local-docker) — do not edit by hand.
# Regenerate by re-running `terraform apply`; source template lives at
# modules/local-docker/templates/prometheus.yml.tpl.

global:
  scrape_interval: ${scrape_interval}

scrape_configs:
  - job_name: "rag-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["${rag_service_container_name}:${rag_service_port}"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
